version: 2
executorType: docker
containerInfo:
  - image: kkarczmarczyk/node-yarn:latest


jobs:
  build:
    workDir: ~/angular-diff-match-patch
    steps:
      - run:
          name: Set NPM token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - checkout
      - run: echo $CIRCLE_TAG
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Submit coverage report
          command: bash <(curl -s https://codecov.io/bash) -r amweiss/angular-diff-match-patch
      - store_test_results:
          path: ./test/results
      - store_artifacts:
          path: ./coverage
          destination: build


deployment:
  fake_deploy_for_cci2:
    tag: /v.*/
    commands:
      - npm publish --tag "${CIRCLE_TAG}"